In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
apps_df = pd.read_csv(r"C:\Users\DELL\Pictures\elevance_skills\play_store_data\apps.csv")

apps_df.head()

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [3]:
apps_df.columns

Index(['Unnamed: 0', 'App', 'Category', 'Rating', 'Reviews', 'Size',
       'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated',
       'Current Ver', 'Android Ver'],
      dtype='object')

In [4]:
apps_df = apps_df.drop(columns=['Unnamed: 0'])

In [5]:
apps_df = apps_df.dropna(
    subset=['Category', 'Installs']
)

In [6]:
apps_df['Installs'] = (
    apps_df['Installs']
    .str.replace(',', '')
    .str.replace('+', '')
)

apps_df['Installs'] = apps_df['Installs'].astype(int)

In [7]:
apps_df[['Category', 'Installs']].head()

         Category  Installs
0  ART_AND_DESIGN     10000
1  ART_AND_DESIGN    500000
2  ART_AND_DESIGN   5000000
3  ART_AND_DESIGN  50000000
4  ART_AND_DESIGN    100000

In [8]:
filtered_df = apps_df[
    ~apps_df['Category'].str.startswith(
        ('A', 'C', 'G', 'S')
    )
]

In [9]:
category_installs = (
    filtered_df
    .groupby('Category')['Installs']
    .sum()
    .reset_index()
)

In [10]:
top_5_categories = (
    category_installs
    .sort_values(
        by='Installs',
        ascending=False
    )
    .head(5)
)

In [11]:
top_5_categories = (
    category_installs
    .sort_values(
        by='Installs',
        ascending=False
    )
    .head(5)
)

In [12]:
top_5_categories

         Category    Installs
21          TOOLS  8001771915
20   PRODUCTIVITY  5793091369
19    PHOTOGRAPHY  4649147655
7          FAMILY  4427941505
23  VIDEO_PLAYERS  3926902720

In [13]:
top_5_categories['Highlight'] = np.where(
    top_5_categories['Installs'] > 1000000,
    'Above 1 Million',
    'Below 1 Million'
)

In [14]:
top_5_categories

         Category    Installs        Highlight
21          TOOLS  8001771915  Above 1 Million
20   PRODUCTIVITY  5793091369  Above 1 Million
19    PHOTOGRAPHY  4649147655  Above 1 Million
7          FAMILY  4427941505  Above 1 Million
23  VIDEO_PLAYERS  3926902720  Above 1 Million

In [15]:
fig = px.bar(
    top_5_categories,
    x='Category',
    y='Installs',
    color='Highlight',
    hover_data=['Installs'],
    title='Top 5 App Categories by Installs'
)

fig.show()

In [16]:
from datetime import datetime, time
from zoneinfo import ZoneInfo

In [17]:
current_time = datetime.now(
    ZoneInfo("Asia/Kolkata")
).time()

start_time = time(18, 0)
end_time = time(20, 0)

In [18]:
if start_time <= current_time <= end_time:

    fig = px.bar(
        top_5_categories,
        x='Category',
        y='Installs',
        color='Highlight',
        hover_data=['Installs'],
        title='Top 5 App Categories by Installs'
    )

    fig.show()